"""empty message

Revision ID: 047df4208817
Revises: f0e8dbf63cb1
Create Date: 2020-10-13 15:32:32.749266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047df4208817'
down_revision = 'f0e8dbf63cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('Show_venues_1_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venues_2_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'venues_2')
    op.drop_column('Show', 'venues_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venues_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venues_2_fkey', 'Show', 'Venue', ['venues_2'], ['id'])
    op.create_foreign_key('Show_venues_1_fkey', 'Show', 'Venue', ['venues_1'], ['id'])
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###
