"""empty message

Revision ID: 048351ecc50c
Revises: be4e6ded517d
Create Date: 2020-10-13 13:50:52.262191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048351ecc50c'
down_revision = 'be4e6ded517d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
