"""empty message

Revision ID: 092194438783
Revises: 048351ecc50c
Create Date: 2020-10-13 14:23:36.084897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092194438783'
down_revision = '048351ecc50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues', sa.Integer(), nullable=True))
    op.drop_constraint('Show_venues_1_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venues'], ['id'])
    op.drop_column('Show', 'venues_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venues_1_fkey', 'Show', 'Venue', ['venues_1'], ['id'])
    op.drop_column('Show', 'venues')
    # ### end Alembic commands ###
