"""empty message

Revision ID: 13620fc2d00b
Revises: f2c41b82aad9
Create Date: 2020-10-18 22:46:06.541800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13620fc2d00b'
down_revision = 'f2c41b82aad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    # ### end Alembic commands ###
