"""empty message

Revision ID: 4351b0f1b03a
Revises: a7cde7e51fab
Create Date: 2020-10-13 12:04:32.699356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4351b0f1b03a'
down_revision = 'a7cde7e51fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues_1', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Show', 'Venue', ['venues_1'], ['id'])
    op.drop_constraint('Venue_upcoming_shows_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_upcoming_shows_fkey', 'Venue', 'Show', ['upcoming_shows'], ['id'])
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venues_1')
    # ### end Alembic commands ###
