"""empty message

Revision ID: 5768a42b2054
Revises: 092194438783
Create Date: 2020-10-13 14:31:23.841071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5768a42b2054'
down_revision = '092194438783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venues_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'venues')
    op.add_column('Venue', sa.Column('past_shows', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['upcoming_shows'], ['id'])
    op.create_foreign_key(None, 'Venue', 'Show', ['past_shows'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.add_column('Show', sa.Column('venues', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_venues_fkey', 'Show', 'Venue', ['venues'], ['id'])
    # ### end Alembic commands ###
