"""empty message

Revision ID: 5e99671c334d
Revises: 99808a360144
Create Date: 2020-10-14 23:50:21.823656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e99671c334d'
down_revision = '99808a360144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues', sa.Integer(), nullable=True))
    op.drop_constraint('Show_venue_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venues'], ['id'])
    op.drop_column('Show', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_fkey', 'Show', 'Venue', ['venue'], ['id'])
    op.drop_column('Show', 'venues')
    # ### end Alembic commands ###
