"""empty message

Revision ID: 76f3da7b50f1
Revises: ff81e71455ea
Create Date: 2020-10-13 07:15:22.365747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f3da7b50f1'
down_revision = 'ff81e71455ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Venue', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
