"""empty message

Revision ID: 7a151b753a7b
Revises: 9a815d3a6a5e
Create Date: 2020-10-13 12:20:09.180570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a151b753a7b'
down_revision = '9a815d3a6a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venues_1_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venues_2_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'venues_1')
    op.drop_column('Show', 'venues_2')
    op.add_column('Venue', sa.Column('past_shows', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['past_shows'], ['id'])
    op.create_foreign_key(None, 'Venue', 'Show', ['upcoming_shows'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.add_column('Show', sa.Column('venues_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venues_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_venues_2_fkey', 'Show', 'Venue', ['venues_2'], ['id'])
    op.create_foreign_key('Show_venues_1_fkey', 'Show', 'Venue', ['venues_1'], ['id'])
    # ### end Alembic commands ###
