"""empty message

Revision ID: 949edf926f7a
Revises: 8b5076081c22
Create Date: 2020-10-14 22:28:04.336587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949edf926f7a'
down_revision = '8b5076081c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue', sa.Integer(), nullable=True))
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue'], ['id'])
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'venue')
    # ### end Alembic commands ###
