"""empty message

Revision ID: be4e6ded517d
Revises: 93c0cde0d9e0
Create Date: 2020-10-13 12:58:11.100540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4e6ded517d'
down_revision = '93c0cde0d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
