"""empty message

Revision ID: e1ca9172e2d8
Revises: 5e99671c334d
Create Date: 2020-10-14 23:50:36.181488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ca9172e2d8'
down_revision = '5e99671c334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue', sa.Integer(), nullable=True))
    op.drop_constraint('Show_venues_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue'], ['id'])
    op.drop_column('Show', 'venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venues', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venues_fkey', 'Show', 'Venue', ['venues'], ['id'])
    op.drop_column('Show', 'venue')
    # ### end Alembic commands ###
