"""empty message

Revision ID: ecbc1de75ef9
Revises: 114b2d92036f
Create Date: 2020-10-13 04:40:15.119528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbc1de75ef9'
down_revision = '114b2d92036f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('area', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Area', ['area'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'num_upcoming_shows')
    op.drop_column('Venue', 'area')
    op.drop_table('Area')
    # ### end Alembic commands ###
