"""empty message

Revision ID: ffc8b14045bc
Revises: e1ca9172e2d8
Create Date: 2020-10-15 00:30:53.432707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc8b14045bc'
down_revision = 'e1ca9172e2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_id', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['past_shows_id'], ['id'])
    op.create_foreign_key(None, 'Venue', 'Show', ['upcoming_shows_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'upcoming_shows_id')
    op.drop_column('Venue', 'past_shows_id')
    # ### end Alembic commands ###
